### ISSUE TITLE
name of the script - generall questions

### ISSUE THREAD

**Issue by howtofixthis** [Selmer443/dotfiles#1]
Hi, I saw your youtube video, awesome rice btw, I just wanted to know the name of the script for toggling the blur on and off because I couldn't find it in the repo. Also what's the package for having fancy cursor animations?

**Comment by Thesecondbestname** [comment]
I think the toggle was Super-shift-Z

**Comment by Selmer443** [comment]
neovide for neovim cursor animation, the script for opacity is in .config/hypr/scripts/toggle_opacity
