### ISSUE TITLE
What font should I use?

### ISSUE THREAD

**Issue by Xyrn23** [Selmer443/dotfiles#3]
just wondering if I apply your configs on my linux machine it will also install the fonts needed to view this special characters?If not what font/s should I install to make them look what they should be. I used my tablet to explore your configs that's why I asked.

![Screenshot_20230209_175317_Chrome](https://user-images.githubusercontent.com/93040266/217780350-6b1200cf-1d9f-45d0-8f41-b7e0d3be0d42.jpg)

**Comment by neomikr0n** [comment]
Not OP, but I use JetBrainsMono Nerd Font, install it then go to your browser and change it there, in arch you will find it as: 
`ttf-jetbrains-mono-nerd`

**Comment by Xyrn23** [comment]
> Not OP, but I use JetBrainsMono Nerd Font, install it then go to your browser and change it there, in arch based distros you will find it as: `ttf-jetbrains-mono-nerd` Let me know if you need help with anything else :)

thanks for replying, I installed it last night and had some problem in installing `spotify-player-dev` also when I use this command `chezmoi init --apply https://github.com/Selmer443/dotfiles.git` it takes forever to finish idk why. so I decided to copy all of them manually. another problem I encountered is the neofetch config those special characters still won't show up even after I install the `JetBrains Nerd Font`
and the default font size in my terminal is bigger than I expected but I know there's an easy fix for that.

**Comment by neomikr0n** [comment]
It seems to me you have a very inquisitive a proactive mindset, you will have a lot of fun with Hyprland. I just peek on the neofetch config and in my browser (Firedragon) and the lines 8 and 10 are not showing the special characters, I copy those lines to VS Code and the issue persist. All the others special characters are shown thought, perhaps there is a more complete font out there, which I'm not aware. It's not enough to install the font, also it's necessary to enable it globally on the settings of each app's desktop environment you are using (KDE settings, nwg-look for gtk, etc.) and for some apps it's necessary to manually set it on their respective configurations (in my case Firedragon and VS Code). Hope makes sense!

**Comment by Xyrn23** [comment]
> neomikr0n

yeah I'm still newbie and thanks for replying!

**Comment by Selmer443** [comment]
hey sorry for the late response, try installing this package from the AUR for the neofetch icons: ttf-material-design-icons-desktop-git
