### ISSUE TITLE
Dual monitor issue

### ISSUE THREAD

**Issue by raminsamadi123** [Selmer443/dotfiles#5]
I have provided a fix for this by creating a pull request for the solution.
I used this:
```sh
monitor=,preferred,auto,1
```
Instead of what you previously used:
```sh
monitor=DP-1,2560x1440@240,0x0,1
monitor=DP-3,1920x1080@240,2560x0,1
```

**Comment by Selmer443** [comment]
Hi, thank you for bringing this up, I will push a solution soon, see my response to the pull request.
